# Tutorial to use with: https://github.com/andry81-devops/github-accum-stats
#

name: "gh-workflow: GitHub clones counter for 14 days at every 8 hours and clones accumulator"

on:
  schedule:
    - cron: "0 */8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-gh-clone-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: andry81-devops/gh-action--accum-gh-stats@master
        with:
          deps_repo_owner:          andry81-devops
          deps_repo_branch:         master
          deps_repo_read_token:     ${{ github.token }}

          stat_repo_owner:          andry81-devops
          stat_repo:                gh-workflow
          stat_entity_path:         traffic/clones
          stat_repo_read_token:     ${{ secrets.READ_STATS_TOKEN }}
          stats_list_key:           clones

          curl_flags: >-
            -H 'Cache-Control: no-cache'

          output_repo_owner:        andry81-stats
          output_repo:              gh-workflow--gh-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/clones
          output_repo_write_token:  ${{ secrets.READ_STATS_TOKEN }}

          env: >-
            ENABLE_GENERATE_CHANGELOG_FILE=1
            ENABLE_COMMIT_MESSAGE_DATE_WITH_TIME=1
