# based on: https://github.com/andry81/github-accum-stats
#

name: "tacklebar: totalcmd board stats updating every 4 hours"

on:
  schedule:
    - cron: "0 */4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-totalcmd-board-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: andry81-devops/gh-action--accum-board-stats@master
        with:
          board_name:               totalcmd
          # CAUTION: Beware of double quotes strip in case of usage yaml `>-` operator or even a single-quotted string!
          topic_query_url:          https://www.ghisler.ch/board/search.php?keywords=\"%5BExtension%5D+Tacklebar\"&terms=all&author=andry81&fid%5B%5D=6&sc=0&sf=titleonly&sr=topics&sk=i&sd=d&st=0&ch=1&t=0&submit=Search
          replies_sed_regexp:       s/.*class=\"posts\"[^0-9]*([0-9.]+).*/\1/p
          views_sed_regexp:         s/.*class=\"views\"[^0-9]*([0-9.]+).*/\1/p

          curl_flags: >-
            -v
            -H 'Cache-Control: no-cache'

          deps_repo_owner:          andry81-devops
          deps_repo_branch:         master
          deps_repo_read_token:     ${{ secrets.READ_STATS_TOKEN }}

          stat_entity_path:         traffic/board/totalcmd

          output_repo_owner:        andry81-stats
          output_repo:              tacklebar--totalcmd-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/board/totalcmd
          output_repo_write_token:  ${{ secrets.READ_STATS_TOKEN }}

          env: >-
            ENABLE_GENERATE_CHANGELOG_FILE=1
            ENABLE_PRINT_CURL_RESPONSE_ON_ERROR=1
